import { ComponentCategory } from '../types'
import type { Component } from '../types'

/**
 * 基础组件列表
 */
const BASIC_COMPONENTS: Component[] = [
  {
    id: '',
    type: 'el-button',
    name: '按钮',
    icon: 'el-icon-thumb',
    category: ComponentCategory.BASIC,
    props: {
      type: 'primary',
      size: 'default',
      text: '按钮',
      round: false,
      plain: false,
      disabled: false,
      icon: '',
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-input',
    name: '输入框',
    icon: 'el-icon-edit',
    category: ComponentCategory.BASIC,
    props: {
      placeholder: '请输入',
      modelValue: '',
      clearable: true,
      disabled: false,
      type: 'text',
      showPassword: false,
      size: 'default',
      maxlength: '',
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-select',
    name: '选择器',
    icon: 'el-icon-arrow-down',
    category: ComponentCategory.BASIC,
    props: {
      placeholder: '请选择',
      modelValue: '',
      clearable: true,
      disabled: false,
      multiple: false,
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-radio-group',
    name: '单选框组',
    icon: 'el-icon-circle-check',
    category: ComponentCategory.BASIC,
    props: {
      modelValue: '',
      disabled: false,
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-checkbox-group',
    name: '多选框组',
    icon: 'el-icon-check',
    category: ComponentCategory.BASIC,
    props: {
      modelValue: [],
      disabled: false,
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-date-picker',
    name: '日期选择器',
    icon: 'el-icon-date',
    category: ComponentCategory.BASIC,
    props: {
      type: 'date',
      placeholder: '选择日期',
      modelValue: '',
      disabled: false,
      clearable: true,
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-time-picker',
    name: '时间选择器',
    icon: 'el-icon-time',
    category: ComponentCategory.BASIC,
    props: {
      placeholder: '选择时间',
      modelValue: '',
      disabled: false,
      clearable: true,
      format: 'HH:mm:ss',
      valueFormat: 'HH:mm:ss',
    },
    rules: [],
  },
  {
    id: '',
    type: 'el-switch',
    name: '开关',
    icon: 'el-icon-open',
    category: ComponentCategory.BASIC,
    props: {
      modelValue: false,
      disabled: false,
      activeText: '',
      inactiveText: '',
      activeColor: '#409EFF',
      inactiveColor: '#C0CCDA',
    },
    rules: [],
  },
]

/**
 * 布局组件列表
 */
const LAYOUT_COMPONENTS: Component[] = [
  {
    id: '',
    type: 'el-row',
    name: '行容器',
    icon: 'el-icon-s-grid',
    category: ComponentCategory.LAYOUT,
    props: {
      gutter: 0,
      justify: 'start',
      align: 'top',
      tag: 'div',
    },
    style: {
      width: '100%',
      minHeight: '50px',
    },
    children: [],
    rules: [
      {
        childrenType: ['el-col'],
      },
    ],
  },
  {
    id: '',
    type: 'el-col',
    name: '列容器',
    icon: 'el-icon-menu',
    category: ComponentCategory.LAYOUT,
    props: {
      span: 24,
      offset: 0,
      pull: 0,
      push: 0,
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
      tag: 'div',
    },
    style: {
      minHeight: '50px',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-container',
          'el-form',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-container',
    name: '容器',
    icon: 'el-icon-s-unfold',
    category: ComponentCategory.LAYOUT,
    props: {
      direction: '',
    },
    style: {
      width: '100%',
      height: '100%',
      minHeight: '200px',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-header',
          'el-aside',
          'el-main',
          'el-footer',
          'el-container',
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-form',
          'el-row',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-header',
    name: '顶栏容器',
    icon: 'el-icon-s-fold',
    category: ComponentCategory.LAYOUT,
    props: {
      height: '60px',
    },
    style: {
      backgroundColor: '#f5f7fa',
      lineHeight: '60px',
      textAlign: 'center',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-form',
          'el-row',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-aside',
    name: '侧边栏容器',
    icon: 'el-icon-s-unfold',
    category: ComponentCategory.LAYOUT,
    props: {
      width: '200px',
    },
    style: {
      backgroundColor: '#f5f7fa',
      minHeight: '200px',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-form',
          'el-row',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-main',
    name: '主要区域容器',
    icon: 'el-icon-s-grid',
    category: ComponentCategory.LAYOUT,
    props: {},
    style: {
      backgroundColor: '#f5f7fa',
      minHeight: '200px',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-form',
          'el-row',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-footer',
    name: '底栏容器',
    icon: 'el-icon-s-fold',
    category: ComponentCategory.LAYOUT,
    props: {
      height: '60px',
    },
    style: {
      backgroundColor: '#f5f7fa',
      lineHeight: '60px',
      textAlign: 'center',
    },
    children: [],
    rules: [
      {
        childrenType: [
          'el-button',
          'el-input',
          'el-select',
          'el-radio-group',
          'el-checkbox-group',
          'el-date-picker',
          'el-time-picker',
          'el-switch',
          'el-divider',
          'el-form',
          'el-row',
          'line-chart',
          'bar-chart',
          'pie-chart',
          'scatter-chart',
        ],
      },
    ],
  },
  {
    id: '',
    type: 'el-divider',
    name: '分割线',
    icon: 'el-icon-minus',
    category: ComponentCategory.LAYOUT,
    props: {
      contentPosition: 'center',
      direction: 'horizontal',
    },
    rules: [],
  },
]

/**
 * 图表组件列表
 */
const CHART_COMPONENTS: Component[] = [
  {
    id: '',
    type: 'line-chart',
    name: '折线图',
    icon: 'el-icon-data-line',
    category: ComponentCategory.CHART,
    props: {
      title: '折线图示例',
      height: '300px',
      dataset: [
        { year: '2016', value: 100 },
        { year: '2017', value: 120 },
        { year: '2018', value: 90 },
        { year: '2019', value: 130 },
        { year: '2020', value: 150 },
        { year: '2021', value: 160 },
        { year: '2022', value: 180 },
      ],
      xField: 'year',
      yField: 'value',
      smooth: true,
      showSymbol: true,
    },
    rules: [],
  },
  {
    id: '',
    type: 'bar-chart',
    name: '柱状图',
    icon: 'el-icon-data-analysis',
    category: ComponentCategory.CHART,
    props: {
      title: '柱状图示例',
      height: '300px',
      dataset: [
        { category: '类别1', value: 100 },
        { category: '类别2', value: 120 },
        { category: '类别3', value: 90 },
        { category: '类别4', value: 130 },
        { category: '类别5', value: 150 },
      ],
      xField: 'category',
      yField: 'value',
      showLabel: true,
    },
    rules: [],
  },
  {
    id: '',
    type: 'pie-chart',
    name: '饼图',
    icon: 'el-icon-pie-chart',
    category: ComponentCategory.CHART,
    props: {
      title: '饼图示例',
      height: '300px',
      dataset: [
        { type: '类别1', value: 27 },
        { type: '类别2', value: 25 },
        { type: '类别3', value: 18 },
        { type: '类别4', value: 15 },
        { type: '类别5', value: 10 },
        { type: '其他', value: 5 },
      ],
      angleField: 'value',
      colorField: 'type',
      radius: 0.8,
      innerRadius: 0,
    },
    rules: [],
  },
  {
    id: '',
    type: 'scatter-chart',
    name: '散点图',
    icon: 'el-icon-coordinate',
    category: ComponentCategory.CHART,
    props: {
      title: '散点图示例',
      height: '300px',
      dataset: [
        { x: 10, y: 8, size: 20, category: 'A' },
        { x: 20, y: 15, size: 40, category: 'A' },
        { x: 30, y: 22, size: 35, category: 'B' },
        { x: 40, y: 30, size: 30, category: 'B' },
        { x: 50, y: 25, size: 25, category: 'C' },
        { x: 60, y: 45, size: 50, category: 'C' },
        { x: 70, y: 60, size: 45, category: 'D' },
      ],
      xField: 'x',
      yField: 'y',
      sizeField: 'size',
      colorField: 'category',
    },
    rules: [],
  },
]

/**
 * 全部组件列表
 */
export const COMPONENT_LIST: Component[] = [
  ...BASIC_COMPONENTS,
  ...LAYOUT_COMPONENTS,
  ...CHART_COMPONENTS,
]
