import type { ComponentDefinition } from '../types';
import {
  Check,
  Edit,
  Message,
  Select,
  Switch,
  Calendar,
  Ship,
  Grid,
  Document,
  Menu,
  Histogram,
  PieChart,
  TrendCharts,
  DataAnalysis,
} from '@element-plus/icons-vue';

/**
 * 基础组件配置常量定义
 * 包含按钮、输入框、选择器等基础组件
 */
export const BASIC_COMPONENTS: ComponentDefinition[] = [
  {
    id: 'el-button',
    name: '按钮',
    type: 'basic',
    icon: 'Check',
    component: 'ElButton',
    initialSize: { width: 120, height: 40 },
    defaultProps: {
      type: 'primary',
      size: 'default',
      text: '按钮',
      round: false,
      disabled: false,
    },
    propsSchema: [
      {
        name: 'text',
        label: '按钮文本',
        type: 'string',
        default: '按钮',
        group: 'basic',
      },
      {
        name: 'type',
        label: '类型',
        type: 'select',
        default: 'primary',
        options: [
          { label: '默认', value: 'default' },
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
        ],
        group: 'basic',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: 'basic',
      },
      {
        name: 'round',
        label: '圆角',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
    ],
  },
  {
    id: 'el-input',
    name: '输入框',
    type: 'basic',
    icon: 'Edit',
    component: 'ElInput',
    initialSize: { width: 200, height: 40 },
    defaultProps: {
      placeholder: '请输入',
      type: 'text',
      clearable: true,
      disabled: false,
      showPassword: false,
    },
    propsSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        default: '请输入',
        group: 'basic',
      },
      {
        name: 'type',
        label: '类型',
        type: 'select',
        default: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '数字', value: 'number' },
          { label: '文本域', value: 'textarea' },
        ],
        group: 'basic',
      },
      {
        name: 'clearable',
        label: '可清空',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'showPassword',
        label: '显示密码切换',
        type: 'boolean',
        default: false,
        visibleIf: { field: 'type', value: 'password' },
        group: 'basic',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
    ],
  },
  {
    id: 'el-select',
    name: '选择器',
    type: 'basic',
    icon: 'Select',
    component: 'ElSelect',
    initialSize: { width: 200, height: 40 },
    defaultProps: {
      placeholder: '请选择',
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
      clearable: true,
      disabled: false,
      multiple: false,
    },
    propsSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        default: '请选择',
        group: 'basic',
      },
      {
        name: 'options',
        label: '选项',
        type: 'array',
        default: [
          { label: '选项1', value: '1' },
          { label: '选项2', value: '2' },
          { label: '选项3', value: '3' },
        ],
        group: 'basic',
      },
      {
        name: 'clearable',
        label: '可清空',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'multiple',
        label: '多选',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
    ],
  },
  {
    id: 'el-switch',
    name: '开关',
    type: 'basic',
    icon: 'Switch',
    component: 'ElSwitch',
    initialSize: { width: 60, height: 40 },
    defaultProps: {
      activeText: '',
      inactiveText: '',
      disabled: false,
      activeColor: '#409EFF',
      inactiveColor: '#C0CCDA',
    },
    propsSchema: [
      {
        name: 'activeText',
        label: '打开文本',
        type: 'string',
        default: '',
        group: 'basic',
      },
      {
        name: 'inactiveText',
        label: '关闭文本',
        type: 'string',
        default: '',
        group: 'basic',
      },
      {
        name: 'activeColor',
        label: '打开颜色',
        type: 'color',
        default: '#409EFF',
        group: 'style',
      },
      {
        name: 'inactiveColor',
        label: '关闭颜色',
        type: 'color',
        default: '#C0CCDA',
        group: 'style',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
    ],
  },
  {
    id: 'el-date-picker',
    name: '日期选择器',
    type: 'basic',
    icon: 'Calendar',
    component: 'ElDatePicker',
    initialSize: { width: 200, height: 40 },
    defaultProps: {
      type: 'date',
      placeholder: '请选择日期',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      clearable: true,
      disabled: false,
    },
    propsSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        default: 'date',
        options: [
          { label: '日期', value: 'date' },
          { label: '日期范围', value: 'daterange' },
          { label: '月份', value: 'month' },
          { label: '月份范围', value: 'monthrange' },
          { label: '年份', value: 'year' },
        ],
        group: 'basic',
      },
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        default: '请选择日期',
        group: 'basic',
      },
      {
        name: 'format',
        label: '显示格式',
        type: 'string',
        default: 'YYYY-MM-DD',
        group: 'basic',
      },
      {
        name: 'valueFormat',
        label: '值格式',
        type: 'string',
        default: 'YYYY-MM-DD',
        group: 'basic',
      },
      {
        name: 'clearable',
        label: '可清空',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        default: false,
        group: 'basic',
      },
    ],
  },
];

/**
 * 布局组件配置常量定义
 * 包含容器、行、列等布局组件
 */
export const LAYOUT_COMPONENTS: ComponentDefinition[] = [
  {
    id: 'el-container',
    name: '容器',
    type: 'layout',
    icon: 'Grid',
    component: 'ElContainer',
    allowChildren: true,
    allowedChildTypes: ['basic', 'layout', 'chart'],
    initialSize: { width: 500, height: 300 },
    defaultProps: {
      direction: 'vertical',
      background: '#ffffff',
      border: true,
    },
    propsSchema: [
      {
        name: 'direction',
        label: '排列方向',
        type: 'select',
        default: 'vertical',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
        ],
        group: 'basic',
      },
      {
        name: 'background',
        label: '背景颜色',
        type: 'color',
        default: '#ffffff',
        group: 'style',
      },
      {
        name: 'border',
        label: '显示边框',
        type: 'boolean',
        default: true,
        group: 'style',
      },
    ],
  },
  {
    id: 'el-row',
    name: '行',
    type: 'layout',
    icon: 'Menu',
    component: 'ElRow',
    allowChildren: true,
    allowedChildTypes: ['basic', 'layout', 'chart'],
    initialSize: { width: 500, height: 100 },
    defaultProps: {
      gutter: 0,
      justify: 'start',
      align: 'top',
    },
    propsSchema: [
      {
        name: 'gutter',
        label: '栅格间隔',
        type: 'number',
        default: 0,
        group: 'basic',
      },
      {
        name: 'justify',
        label: '水平排列',
        type: 'select',
        default: 'start',
        options: [
          { label: '左对齐', value: 'start' },
          { label: '右对齐', value: 'end' },
          { label: '居中', value: 'center' },
          { label: '两端对齐', value: 'space-between' },
          { label: '均匀分布', value: 'space-around' },
        ],
        group: 'basic',
      },
      {
        name: 'align',
        label: '垂直排列',
        type: 'select',
        default: 'top',
        options: [
          { label: '顶部对齐', value: 'top' },
          { label: '居中对齐', value: 'middle' },
          { label: '底部对齐', value: 'bottom' },
        ],
        group: 'basic',
      },
    ],
  },
  {
    id: 'el-col',
    name: '列',
    type: 'layout',
    icon: 'Document',
    component: 'ElCol',
    allowChildren: true,
    allowedChildTypes: ['basic', 'layout', 'chart'],
    initialSize: { width: 200, height: 100 },
    defaultProps: {
      span: 12,
      offset: 0,
      background: 'transparent',
    },
    propsSchema: [
      {
        name: 'span',
        label: '栅格占据列数',
        type: 'slider',
        default: 12,
        min: 1,
        max: 24,
        group: 'basic',
      },
      {
        name: 'offset',
        label: '栅格左侧偏移',
        type: 'slider',
        default: 0,
        min: 0,
        max: 24,
        group: 'basic',
      },
      {
        name: 'background',
        label: '背景颜色',
        type: 'color',
        default: 'transparent',
        group: 'style',
      },
    ],
  },
];

/**
 * 图表组件配置常量定义
 * 包含柱状图、折线图、饼图等图表组件
 */
export const CHART_COMPONENTS: ComponentDefinition[] = [
  {
    id: 'echarts-bar',
    name: '柱状图',
    type: 'chart',
    icon: 'Histogram',
    component: 'EchartsBar',
    initialSize: { width: 400, height: 300 },
    defaultProps: {
      title: '柱状图',
      xAxisName: 'X轴',
      yAxisName: 'Y轴',
      showLegend: true,
      data: [
        { name: '类别1', value: 120 },
        { name: '类别2', value: 200 },
        { name: '类别3', value: 150 },
        { name: '类别4', value: 80 },
        { name: '类别5', value: 170 },
      ],
    },
    propsSchema: [
      {
        name: 'title',
        label: '图表标题',
        type: 'string',
        default: '柱状图',
        group: 'basic',
      },
      {
        name: 'xAxisName',
        label: 'X轴名称',
        type: 'string',
        default: 'X轴',
        group: 'basic',
      },
      {
        name: 'yAxisName',
        label: 'Y轴名称',
        type: 'string',
        default: 'Y轴',
        group: 'basic',
      },
      {
        name: 'showLegend',
        label: '显示图例',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'data',
        label: '数据',
        type: 'array',
        default: [
          { name: '类别1', value: 120 },
          { name: '类别2', value: 200 },
          { name: '类别3', value: 150 },
          { name: '类别4', value: 80 },
          { name: '类别5', value: 170 },
        ],
        group: 'data',
      },
    ],
  },
  {
    id: 'echarts-line',
    name: '折线图',
    type: 'chart',
    icon: 'TrendCharts',
    component: 'EchartsLine',
    initialSize: { width: 400, height: 300 },
    defaultProps: {
      title: '折线图',
      xAxisName: 'X轴',
      yAxisName: 'Y轴',
      smooth: true,
      showLegend: true,
      data: [
        { name: '1月', value: 120 },
        { name: '2月', value: 132 },
        { name: '3月', value: 101 },
        { name: '4月', value: 134 },
        { name: '5月', value: 90 },
        { name: '6月', value: 230 },
      ],
    },
    propsSchema: [
      {
        name: 'title',
        label: '图表标题',
        type: 'string',
        default: '折线图',
        group: 'basic',
      },
      {
        name: 'xAxisName',
        label: 'X轴名称',
        type: 'string',
        default: 'X轴',
        group: 'basic',
      },
      {
        name: 'yAxisName',
        label: 'Y轴名称',
        type: 'string',
        default: 'Y轴',
        group: 'basic',
      },
      {
        name: 'smooth',
        label: '平滑曲线',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'showLegend',
        label: '显示图例',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'data',
        label: '数据',
        type: 'array',
        default: [
          { name: '1月', value: 120 },
          { name: '2月', value: 132 },
          { name: '3月', value: 101 },
          { name: '4月', value: 134 },
          { name: '5月', value: 90 },
          { name: '6月', value: 230 },
        ],
        group: 'data',
      },
    ],
  },
  {
    id: 'echarts-pie',
    name: '饼图',
    type: 'chart',
    icon: 'PieChart',
    component: 'EchartsPie',
    initialSize: { width: 400, height: 300 },
    defaultProps: {
      title: '饼图',
      showLegend: true,
      radius: '60%',
      data: [
        { name: '类别1', value: 335 },
        { name: '类别2', value: 310 },
        { name: '类别3', value: 234 },
        { name: '类别4', value: 135 },
        { name: '类别5', value: 1548 },
      ],
    },
    propsSchema: [
      {
        name: 'title',
        label: '图表标题',
        type: 'string',
        default: '饼图',
        group: 'basic',
      },
      {
        name: 'showLegend',
        label: '显示图例',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'radius',
        label: '饼图半径',
        type: 'string',
        default: '60%',
        group: 'basic',
      },
      {
        name: 'data',
        label: '数据',
        type: 'array',
        default: [
          { name: '类别1', value: 335 },
          { name: '类别2', value: 310 },
          { name: '类别3', value: 234 },
          { name: '类别4', value: 135 },
          { name: '类别5', value: 1548 },
        ],
        group: 'data',
      },
    ],
  },
  {
    id: 'g2-scatter',
    name: '散点图',
    type: 'chart',
    icon: 'DataAnalysis',
    component: 'G2Scatter',
    initialSize: { width: 400, height: 300 },
    defaultProps: {
      title: '散点图',
      xAxisName: 'X轴',
      yAxisName: 'Y轴',
      showLegend: true,
      data: [
        { x: 10, y: 8, size: 20, category: 'A' },
        { x: 15, y: 13, size: 40, category: 'A' },
        { x: 20, y: 15, size: 30, category: 'B' },
        { x: 25, y: 25, size: 50, category: 'B' },
        { x: 30, y: 18, size: 20, category: 'C' },
      ],
    },
    propsSchema: [
      {
        name: 'title',
        label: '图表标题',
        type: 'string',
        default: '散点图',
        group: 'basic',
      },
      {
        name: 'xAxisName',
        label: 'X轴名称',
        type: 'string',
        default: 'X轴',
        group: 'basic',
      },
      {
        name: 'yAxisName',
        label: 'Y轴名称',
        type: 'string',
        default: 'Y轴',
        group: 'basic',
      },
      {
        name: 'showLegend',
        label: '显示图例',
        type: 'boolean',
        default: true,
        group: 'basic',
      },
      {
        name: 'data',
        label: '数据',
        type: 'array',
        default: [
          { x: 10, y: 8, size: 20, category: 'A' },
          { x: 15, y: 13, size: 40, category: 'A' },
          { x: 20, y: 15, size: 30, category: 'B' },
          { x: 25, y: 25, size: 50, category: 'B' },
          { x: 30, y: 18, size: 20, category: 'C' },
        ],
        group: 'data',
      },
    ],
  },
];

/**
 * 所有组件类型的集合
 */
export const ALL_COMPONENTS = [...BASIC_COMPONENTS, ...LAYOUT_COMPONENTS, ...CHART_COMPONENTS]; 