export type languageType
  = | 'js'
    | 'javascript'
    | 'jsx'
    | 'ts'
    | 'typescript'
    | 'tsx'
    | 'sql'
    | 'mysql'
    | 'postgres'
    | 'postgresql'
    | 'mssql'
    | 'plsql'
    | 'oracle'
    | 'sqlite'
    | 'mariadb'
export type themeType
  = 'vs' | 'hc-black' | 'vs-dark'
