export type langType
  = | 'js'
    | 'javascript'
    | 'jsx'
    | 'ts'
    | 'typescript'
    | 'tsx'
    | 'sql'
    | 'mysql'
    | 'postgres'
    | 'postgresql'
    | 'mssql'
    | 'plsql'
    | 'oracle'
    | 'sqlite'
    | 'mariadb'
