#!/usr/bin/env sh
 . "${PWD}/$(dirname -- "$0")/_/husky.sh"

# git commit的时候做什么事情
 COMMIT_LOCATION="${PWD}/.git/COMMIT_EDITMSG"
 if [ -f "$COMMIT_LOCATION" ]; then
   npx --no-install commitlint --edit "${COMMIT_LOCATION}"
 else
   npx --no-install commitlint --edit "$1"
 fi
