#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 设置要推送的远程仓库和分支
REMOTE_NAME="vitepress-origin"
BRANCH_TO_PUSH="docs"
REMOTE_URL="https://github.com/componentProject/vue-component-vite.git"

# 获取当前分支的最新提交哈希
COMMIT_HASH=$(git rev-parse HEAD)

# 检查远程仓库是否存在
if ! git remote | grep -q "$REMOTE_NAME"; then
    git remote add "$REMOTE_NAME" "$REMOTE_URL"
fi

# 推送更改到另一个远程仓库的指定分支
git push "$REMOTE_NAME" "$COMMIT_HASH:$BRANCH_TO_PUSH" --force